### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np


In [3]:
n = int(input("введите целое число > 0: "))
a = np.arange(n, -1, -1)
print(a)

введите целое число > 0: 9
[9 8 7 6 5 4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
n = int(input("введите целое число > 0: "))
a = np.diag(np.arange(n, -1, -1), k=0)
elem_= np.diagonal(a)
sum_ = np.trace(a)
print(a,'\n', "Значения главной диагонали: ", (elem_), '\n', "Cумма значений главной диагонали: ", sum_)

введите целое число > 0: 5
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]] 
 Значения главной диагонали:  [5 4 3 2 1 0] 
 Cумма значений главной диагонали:  15


### Задание 3
Решите систему уравнений:
###### 4x + 2y + z = 4
###### x + 3y = 12
###### 5y + 4z = -3

In [5]:
M1 = np.array([[4., 2., 1.], [1., 3., 0.],[0., 5., 4.]]) # Матрица (левая часть системы)
v1 = np.array([4., 12., -3.]) # Вектор (правая часть системы)
np.linalg.solve(M1, v1)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. Матрица в виде numpy array 
##### users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
##### На сайт заходит очередной посетитель, о покупках которого известно следующее:
##### next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [6]:
users_stats = np.array(
        [
           [2, 1, 0, 0, 0, 0],
           [1, 1, 2, 1, 0, 0],
           [2, 0, 1, 0, 0, 0],
           [1, 1, 2, 1, 0, 1],
           [0, 0, 1, 2, 0, 0],
           [0, 0, 0, 0, 0, 5],
           [1, 0, 0, 0, 0, 0],
           [0, 1, 1, 0, 0, 0],
           [0, 0, 0, 1, 1, 3],
           [1, 0, 0, 2, 1, 4],
       ])

next_user_stats   = np.array([0, 1, 2, 0, 0, 0])
length_V = np.linalg.norm(next_user_stats) 
def cousine(users_stats, next_user_stats):
  for i in range(len(users_stats)):
    length_V1 = np.linalg.norm(users_stats[i]) 
    print((np.dot(users_stats[i], next_user_stats))/(length_V1*length_V))
  return

cousine(users_stats, next_user_stats)

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
